// <auto-generated />
using System;
using FinanceManager.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("db3e695c-2f84-47ec-8a36-8e2c51b7a53f"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("06a12d9c-20a2-4f39-8c13-68e0bdddbadb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80d4821b-a1af-46c1-9f77-1a5944986781",
                            CreatedOn = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastModifiedOn = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIIxUvMVY6oY0tlAwFQ0HUNxuvIr69wfrlEBJ9f40ZruSVn5rMMO6DGsQXjnxpqd+w==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "c97bbf70-a83e-473a-af00-04c15aa3cccb",
                            TwoFactorEnabled = false,
                            UserName = "john.doe@example.com"
                        },
                        new
                        {
                            Id = new Guid("6085ec7e-1cd3-4302-a51e-0a216c738b79"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ac599c11-794f-467c-bf93-04f9ff4931dc",
                            CreatedOn = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastModifiedOn = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPDowkUQB13Knk1V4+rnruh2byGx8L8cqKvwQ2+UMOw3JCa9ShqTLmYmA/skAbhOKA==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "60b771a0-af7e-4527-a114-dfb8b30e472b",
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@example.com"
                        },
                        new
                        {
                            Id = new Guid("b9d052fd-c677-4722-85ff-0a2a5aad4af1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f5b3868-7240-436c-8483-0607bf9e935e",
                            CreatedOn = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.johnson@example.com",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            LastModifiedOn = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAEL.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECokPx1Uymcti3CW/v3fdFQTpVCOjd7iZT3Ksi5bMhhzgIKgfF2CFLYcwu9zMGjqJw==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "3057898e-7200-475b-9083-9d1e7142268a",
                            TwoFactorEnabled = false,
                            UserName = "michael.johnson@example.com"
                        },
                        new
                        {
                            Id = new Guid("47b38d98-ee54-409b-bf0b-2821ca8a20b0"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7138a660-62c7-4ef9-87af-44d5a8550c37",
                            CreatedOn = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emily",
                            LastModifiedOn = new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.DAVIS@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFV/CxCbKIxEXNYGpT6X7cIdakSqh1SVcXCGdHESZNH3XvRSdHbQCITRXUI4RbAm6g==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "385b0441-84e4-4f0a-8752-495f2f4d005a",
                            TwoFactorEnabled = false,
                            UserName = "emily.davis@example.com"
                        },
                        new
                        {
                            Id = new Guid("00039684-7db3-46ff-a0f5-b744f225c30e"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a890519d-223c-4045-b1b2-9f2cbdc19026",
                            CreatedOn = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chris.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Chris",
                            LastModifiedOn = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "CHRIS.BROWN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJvOykoneIGxU88zwOYxNt96EkeAcPk7vG1xxISO/4rjfbFuctUXupCikXZlkJr8cQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "a18de4ad-5064-49ac-b5ef-81cde6d2827a",
                            TwoFactorEnabled = false,
                            UserName = "chris.brown@example.com"
                        },
                        new
                        {
                            Id = new Guid("0c2fb4ea-d631-4ce7-9f02-2f4c011c2160"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33ebfde7-a6ce-4046-92b0-4685e201446a",
                            CreatedOn = new DateTime(2023, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mr.admin.number1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastModifiedOn = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Your best",
                            LockoutEnabled = false,
                            NormalizedEmail = "MR.ADMIN.NUMBER1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOHpil2TDHMZFj4SOTBmZsHNlLXT8uPAItWOhVbI5DSNr3iUx3NArdiX9ibKVHbmVQ==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "5a0b7512-1f5e-499e-af17-8cb21455020e",
                            TwoFactorEnabled = false,
                            UserName = "mr.admin.number1@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("1749fadd-b32e-430d-80d4-68b041218bd3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4b9d5a46-bc36-4b59-85ec-1b7af917af1d",
                            CreatedOn = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mr.admin.number2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastModifiedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Your second best",
                            LockoutEnabled = false,
                            NormalizedEmail = "MR.ADMIN.NUMBER2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF+8duMuJjfQRTPUnVJetBaLU13SmWKUJVdqj/mvRY67feCA6542H0RCCqjjgRHSKw==",
                            PhoneNumberConfirmed = false,
                            RefreshToken = "",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "02d399e5-bd6f-4d76-bde1-162e2b4c9074",
                            TwoFactorEnabled = false,
                            UserName = "mr.admin.number2@gmail.com"
                        });
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.FinanceOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("FinanceOperations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53f8ff92-eb4f-477c-8958-57242e4f86d6"),
                            Amount = 500L,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("53f6f158-150b-4236-b990-b532ac7e8fc2"),
                            Amount = 100L,
                            Date = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e7d6760c-92d3-4130-b4d6-5ad459880399")
                        },
                        new
                        {
                            Id = new Guid("18cb485c-03ea-4def-a07b-d7ca43621a4f"),
                            Amount = 750L,
                            Date = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b924b2e9-f504-4bc6-a611-ce856b2b1fdd")
                        },
                        new
                        {
                            Id = new Guid("2ee651a3-c5fd-4ddc-8d1d-8d05c2aeb72e"),
                            Amount = 120L,
                            Date = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("07833ef4-9b71-4457-92f1-8cd3ea331630")
                        },
                        new
                        {
                            Id = new Guid("add52289-1be1-481c-845a-c6b041f3737c"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d8179f7e-9789-4be3-a1c2-5c536c5d384b")
                        },
                        new
                        {
                            Id = new Guid("96d4e692-c511-4d3d-97a8-2d45e49d67db"),
                            Amount = 60L,
                            Date = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("663171ac-1ac1-461d-b45a-469e644c9ae4")
                        },
                        new
                        {
                            Id = new Guid("685c6761-473a-44e1-aafb-431eb7ff4daa"),
                            Amount = 40L,
                            Date = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("cc488c25-5e5d-4ae1-9cca-7842effad853")
                        },
                        new
                        {
                            Id = new Guid("de48d422-feb0-4dd3-a4ca-5e85e4f23bfc"),
                            Amount = 100L,
                            Date = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e21e180c-29e3-412a-99f3-b7254a6c6a1b")
                        },
                        new
                        {
                            Id = new Guid("18f2a06f-9155-47ac-8a94-51ee0a6f5c55"),
                            Amount = 2000L,
                            Date = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e95da595-58b3-4726-97b7-d752323d594e")
                        },
                        new
                        {
                            Id = new Guid("491bb2df-bb14-43a7-93a7-b8cba9d8a486"),
                            Amount = 300L,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("afd56f2e-2660-4363-9321-645d93fa0520")
                        },
                        new
                        {
                            Id = new Guid("4b8a4859-6712-4ee9-91b1-1502d20e8a55"),
                            Amount = 150L,
                            Date = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4af51eea-e862-4caf-8ce5-9ad6737dbd7b")
                        },
                        new
                        {
                            Id = new Guid("01f3819a-7ba0-419f-95f0-0ac3417b79d4"),
                            Amount = 200L,
                            Date = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("eb00cc66-2104-4bc4-9d6b-fc20f2cdc935")
                        },
                        new
                        {
                            Id = new Guid("43b9ab73-31bd-468b-87e7-ccf6c13cf2ba"),
                            Amount = 300L,
                            Date = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e1941e45-3981-454d-af77-46be20eb8f90")
                        },
                        new
                        {
                            Id = new Guid("a649dea4-79bc-4f2d-bec9-9046b4e5638f"),
                            Amount = 70L,
                            Date = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("ce0b9d6d-d470-4cc2-8d3e-5ad21aca29a4")
                        },
                        new
                        {
                            Id = new Guid("6cb00bb9-29a0-4a8b-ad8d-9e5f2f5f1f4a"),
                            Amount = 50L,
                            Date = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3d033511-8700-4f2a-a6f2-e47ce51e2bf3")
                        },
                        new
                        {
                            Id = new Guid("46ca599b-0a4a-417b-bc15-863426782ec1"),
                            Amount = 1000L,
                            Date = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("0ebd2a28-9726-4f28-b5a9-707410ef2ad2")
                        },
                        new
                        {
                            Id = new Guid("f40357b5-4cfa-48ea-a221-b7b1476ebcf9"),
                            Amount = 200L,
                            Date = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("76dda505-b8db-4980-8156-ce3056018b97")
                        },
                        new
                        {
                            Id = new Guid("09eb8091-6a30-4455-a845-ae36868da876"),
                            Amount = 250L,
                            Date = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("2b9da575-54ea-4689-bae0-cfe923ac47b2")
                        },
                        new
                        {
                            Id = new Guid("18c66de8-0ef7-4ecc-98b2-e4e0b2c79deb"),
                            Amount = 80L,
                            Date = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("629021c3-fe72-447a-b80a-33670d2f8bbd")
                        },
                        new
                        {
                            Id = new Guid("ee8e2b8b-2284-42e7-8291-dd0516e54135"),
                            Amount = 50L,
                            Date = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("02261ce9-14ba-478b-b522-2cc28790ecf7")
                        },
                        new
                        {
                            Id = new Guid("79b7b04f-135f-4c22-8c03-c36951b7ebce"),
                            Amount = 300L,
                            Date = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("6ae5a115-3361-4b6f-84cb-61fd53f18358")
                        },
                        new
                        {
                            Id = new Guid("02cda2d7-4b3e-4ef9-a842-69ed5ec00513"),
                            Amount = 500L,
                            Date = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("adcbf657-efee-4666-a179-e5a105a1b99d")
                        },
                        new
                        {
                            Id = new Guid("ce9a4ba0-d603-4f07-bf55-aa5019dddc8d"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4b3af6df-8abe-42a1-82e0-ae861a9a33ed")
                        },
                        new
                        {
                            Id = new Guid("2c547dc3-9c98-4206-abe7-83610daa04d4"),
                            Amount = 40L,
                            Date = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f51e1eb6-539a-4e71-9e12-4d8c50fd92b2")
                        },
                        new
                        {
                            Id = new Guid("c57eae65-99d3-45cc-96e3-85d430cb28e7"),
                            Amount = 600L,
                            Date = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b3b31e78-aeaf-468e-baca-3367045ae65b")
                        },
                        new
                        {
                            Id = new Guid("1e49d023-ff93-460c-9701-bbdba9499956"),
                            Amount = 100L,
                            Date = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("5fd4afed-3409-4e18-8118-d0bcf847f11f")
                        },
                        new
                        {
                            Id = new Guid("abedd12b-bc63-4045-8209-4775f1cd36eb"),
                            Amount = 400L,
                            Date = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d849a3fd-5e3a-4365-92df-79e59b732247")
                        },
                        new
                        {
                            Id = new Guid("0067dff5-a986-43f4-8868-ac9b16f2a606"),
                            Amount = 300L,
                            Date = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3cd3e963-5f1c-4026-8cac-f8b097d2be02")
                        },
                        new
                        {
                            Id = new Guid("a7fe2858-ea78-46e2-a57f-c16cdb1d3e8b"),
                            Amount = 500L,
                            Date = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b9bf0cdb-2390-4f19-9955-db8bad50574f")
                        },
                        new
                        {
                            Id = new Guid("7220f6cf-915e-4e5e-a038-ca30824f5819"),
                            Amount = 20L,
                            Date = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("820daebd-f027-4a39-bbcb-289b2d161933")
                        },
                        new
                        {
                            Id = new Guid("f0978cee-bf2a-4c34-b561-bbe11a448696"),
                            Amount = 500L,
                            Date = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("845d05ac-9021-4d5b-98a3-f847480204e6"),
                            Amount = 100L,
                            Date = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e7d6760c-92d3-4130-b4d6-5ad459880399")
                        },
                        new
                        {
                            Id = new Guid("2e310c71-f84f-4fbf-94b4-b637e255714a"),
                            Amount = 750L,
                            Date = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b924b2e9-f504-4bc6-a611-ce856b2b1fdd")
                        },
                        new
                        {
                            Id = new Guid("634462d1-a699-4e0c-b5e1-cd60a69d9c83"),
                            Amount = 120L,
                            Date = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("07833ef4-9b71-4457-92f1-8cd3ea331630")
                        },
                        new
                        {
                            Id = new Guid("b80550d8-6fc3-455a-8cee-c3494bc61b77"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d8179f7e-9789-4be3-a1c2-5c536c5d384b")
                        },
                        new
                        {
                            Id = new Guid("b59cf982-b578-45a9-a23b-6b45d2bd7692"),
                            Amount = 60L,
                            Date = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("663171ac-1ac1-461d-b45a-469e644c9ae4")
                        },
                        new
                        {
                            Id = new Guid("ad7a768d-48d7-4205-a867-4c8a22793d2e"),
                            Amount = 40L,
                            Date = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("cc488c25-5e5d-4ae1-9cca-7842effad853")
                        },
                        new
                        {
                            Id = new Guid("bc670c6d-6bc8-4636-b6aa-191a888d08ed"),
                            Amount = 100L,
                            Date = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e21e180c-29e3-412a-99f3-b7254a6c6a1b")
                        },
                        new
                        {
                            Id = new Guid("c4fb9e32-8e3c-4e04-b2e8-8a65b9e6b790"),
                            Amount = 2000L,
                            Date = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e95da595-58b3-4726-97b7-d752323d594e")
                        },
                        new
                        {
                            Id = new Guid("89e1888d-977c-4f8a-aa6f-7bbe5b6c249e"),
                            Amount = 300L,
                            Date = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("afd56f2e-2660-4363-9321-645d93fa0520")
                        },
                        new
                        {
                            Id = new Guid("a6aff005-135d-49d3-8fad-48da11781fb8"),
                            Amount = 150L,
                            Date = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4af51eea-e862-4caf-8ce5-9ad6737dbd7b")
                        },
                        new
                        {
                            Id = new Guid("491af7ec-1020-4fbd-8986-54d8bbd83b26"),
                            Amount = 200L,
                            Date = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("eb00cc66-2104-4bc4-9d6b-fc20f2cdc935")
                        },
                        new
                        {
                            Id = new Guid("e55f6c51-07c5-4fd6-8a4c-b01ba99146dd"),
                            Amount = 300L,
                            Date = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e1941e45-3981-454d-af77-46be20eb8f90")
                        },
                        new
                        {
                            Id = new Guid("c55d9f3c-887e-4ce5-9058-e6d28d357fa5"),
                            Amount = 70L,
                            Date = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("ce0b9d6d-d470-4cc2-8d3e-5ad21aca29a4")
                        },
                        new
                        {
                            Id = new Guid("f7120ee1-8f4b-49c5-876f-b212e283e95d"),
                            Amount = 50L,
                            Date = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3d033511-8700-4f2a-a6f2-e47ce51e2bf3")
                        },
                        new
                        {
                            Id = new Guid("6564de83-6c2b-4830-ae07-a81820de0283"),
                            Amount = 1000L,
                            Date = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("0ebd2a28-9726-4f28-b5a9-707410ef2ad2")
                        },
                        new
                        {
                            Id = new Guid("fa521fcc-3fc5-4952-9a88-3eddb8e40d5d"),
                            Amount = 200L,
                            Date = new DateTime(2025, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("76dda505-b8db-4980-8156-ce3056018b97")
                        },
                        new
                        {
                            Id = new Guid("ed909415-0823-4a3d-9113-6ce38ffccdd9"),
                            Amount = 250L,
                            Date = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("2b9da575-54ea-4689-bae0-cfe923ac47b2")
                        },
                        new
                        {
                            Id = new Guid("45abda13-29a3-48af-ac99-67df7de3aaeb"),
                            Amount = 80L,
                            Date = new DateTime(2025, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("629021c3-fe72-447a-b80a-33670d2f8bbd")
                        },
                        new
                        {
                            Id = new Guid("404a2a3c-4862-4dbe-a6e4-8a9891e94406"),
                            Amount = 50L,
                            Date = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("02261ce9-14ba-478b-b522-2cc28790ecf7")
                        },
                        new
                        {
                            Id = new Guid("1c926c88-a80c-4850-a341-56cab0bc259f"),
                            Amount = 300L,
                            Date = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("6ae5a115-3361-4b6f-84cb-61fd53f18358")
                        },
                        new
                        {
                            Id = new Guid("b492ea09-2c11-4933-8eb6-e51442b390d7"),
                            Amount = 500L,
                            Date = new DateTime(2025, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("adcbf657-efee-4666-a179-e5a105a1b99d")
                        },
                        new
                        {
                            Id = new Guid("964a41ef-194e-4df6-88ca-4f215de12c5c"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4b3af6df-8abe-42a1-82e0-ae861a9a33ed")
                        },
                        new
                        {
                            Id = new Guid("06bc9f56-a0af-4f33-9ec2-f8a51b293b3c"),
                            Amount = 40L,
                            Date = new DateTime(2025, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f51e1eb6-539a-4e71-9e12-4d8c50fd92b2")
                        },
                        new
                        {
                            Id = new Guid("0f3952ab-f050-45d6-a28b-2a371881f9da"),
                            Amount = 600L,
                            Date = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b3b31e78-aeaf-468e-baca-3367045ae65b")
                        },
                        new
                        {
                            Id = new Guid("8180b6f9-c0b0-4145-a99c-81ad7d78375a"),
                            Amount = 100L,
                            Date = new DateTime(2025, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("5fd4afed-3409-4e18-8118-d0bcf847f11f")
                        },
                        new
                        {
                            Id = new Guid("10ab94e4-7d92-4c40-bae9-201eca72dce5"),
                            Amount = 400L,
                            Date = new DateTime(2025, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d849a3fd-5e3a-4365-92df-79e59b732247")
                        },
                        new
                        {
                            Id = new Guid("e67638bc-c719-4c96-9817-fa933522f1e9"),
                            Amount = 300L,
                            Date = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3cd3e963-5f1c-4026-8cac-f8b097d2be02")
                        },
                        new
                        {
                            Id = new Guid("7d944af6-f97b-4907-b0a3-e32624bc1da9"),
                            Amount = 20L,
                            Date = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("820daebd-f027-4a39-bbcb-289b2d161933")
                        },
                        new
                        {
                            Id = new Guid("cd6231f8-8446-4655-b0a8-3626ace08224"),
                            Amount = 500L,
                            Date = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("bfcb2175-4b9e-4518-8508-adfc30b31e1b"),
                            Amount = 100L,
                            Date = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e7d6760c-92d3-4130-b4d6-5ad459880399")
                        },
                        new
                        {
                            Id = new Guid("54d692ac-36c7-47fd-b006-ee80ccee1f23"),
                            Amount = 750L,
                            Date = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b924b2e9-f504-4bc6-a611-ce856b2b1fdd")
                        },
                        new
                        {
                            Id = new Guid("e149ab0a-887c-4a0f-b344-ebcf878376fa"),
                            Amount = 120L,
                            Date = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("07833ef4-9b71-4457-92f1-8cd3ea331630")
                        },
                        new
                        {
                            Id = new Guid("39ec7582-af93-419b-9996-f9fadf1c98af"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d8179f7e-9789-4be3-a1c2-5c536c5d384b")
                        },
                        new
                        {
                            Id = new Guid("f1ed0d67-df89-4713-b579-267c19fe9b14"),
                            Amount = 60L,
                            Date = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("663171ac-1ac1-461d-b45a-469e644c9ae4")
                        },
                        new
                        {
                            Id = new Guid("c57af14d-06b2-47c0-8d43-3f33af46881f"),
                            Amount = 40L,
                            Date = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("cc488c25-5e5d-4ae1-9cca-7842effad853")
                        },
                        new
                        {
                            Id = new Guid("e9ddf285-8fd4-4d66-8a46-dae1d7648820"),
                            Amount = 100L,
                            Date = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e21e180c-29e3-412a-99f3-b7254a6c6a1b")
                        },
                        new
                        {
                            Id = new Guid("a7276103-8168-4f79-98f5-81f8bd87b626"),
                            Amount = 2000L,
                            Date = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e95da595-58b3-4726-97b7-d752323d594e")
                        },
                        new
                        {
                            Id = new Guid("a903f194-9377-4329-9158-ead5073a837d"),
                            Amount = 300L,
                            Date = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("afd56f2e-2660-4363-9321-645d93fa0520")
                        },
                        new
                        {
                            Id = new Guid("7f9a8913-7f3f-4bb0-9d70-a6e41df6a4ef"),
                            Amount = 150L,
                            Date = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4af51eea-e862-4caf-8ce5-9ad6737dbd7b")
                        },
                        new
                        {
                            Id = new Guid("ba18b0e2-f166-4bb8-bc1d-48354b409b85"),
                            Amount = 200L,
                            Date = new DateTime(2025, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("eb00cc66-2104-4bc4-9d6b-fc20f2cdc935")
                        },
                        new
                        {
                            Id = new Guid("4b9d9ac3-2d50-42ce-bea4-530dd276b061"),
                            Amount = 300L,
                            Date = new DateTime(2025, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e1941e45-3981-454d-af77-46be20eb8f90")
                        },
                        new
                        {
                            Id = new Guid("78d9c3d5-7f48-47a0-9aec-af9d1da592bc"),
                            Amount = 70L,
                            Date = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("ce0b9d6d-d470-4cc2-8d3e-5ad21aca29a4")
                        },
                        new
                        {
                            Id = new Guid("c849eab5-1af0-4c40-b3fa-68cd7c46bfb0"),
                            Amount = 50L,
                            Date = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3d033511-8700-4f2a-a6f2-e47ce51e2bf3")
                        },
                        new
                        {
                            Id = new Guid("443acc27-6474-476d-b8eb-5ea42ddac004"),
                            Amount = 1000L,
                            Date = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("0ebd2a28-9726-4f28-b5a9-707410ef2ad2")
                        },
                        new
                        {
                            Id = new Guid("12892252-a531-4c15-80ea-2a4b7b4862e3"),
                            Amount = 200L,
                            Date = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("76dda505-b8db-4980-8156-ce3056018b97")
                        },
                        new
                        {
                            Id = new Guid("798aa941-fcc3-4337-bd00-8b4ae7c5b7a3"),
                            Amount = 250L,
                            Date = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("2b9da575-54ea-4689-bae0-cfe923ac47b2")
                        },
                        new
                        {
                            Id = new Guid("600f4589-9337-402f-8c18-c755e9717ff2"),
                            Amount = 80L,
                            Date = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("629021c3-fe72-447a-b80a-33670d2f8bbd")
                        },
                        new
                        {
                            Id = new Guid("6ba9a10b-c1df-4ad0-94dd-c7f1a84a0a28"),
                            Amount = 50L,
                            Date = new DateTime(2025, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("02261ce9-14ba-478b-b522-2cc28790ecf7")
                        },
                        new
                        {
                            Id = new Guid("9d56b370-dc8a-427c-bbbb-697e1cb846a8"),
                            Amount = 300L,
                            Date = new DateTime(2025, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("6ae5a115-3361-4b6f-84cb-61fd53f18358")
                        },
                        new
                        {
                            Id = new Guid("a686b4a8-70d5-48be-89b5-7e1b7fabe0cc"),
                            Amount = 500L,
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("adcbf657-efee-4666-a179-e5a105a1b99d")
                        },
                        new
                        {
                            Id = new Guid("7895034f-9c3e-4583-be3d-de3ded0ad5cc"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("4b3af6df-8abe-42a1-82e0-ae861a9a33ed")
                        },
                        new
                        {
                            Id = new Guid("548050b8-0f48-49e4-af12-5b2e5c78d3a1"),
                            Amount = 40L,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f51e1eb6-539a-4e71-9e12-4d8c50fd92b2")
                        },
                        new
                        {
                            Id = new Guid("a0ac6ed0-425e-4afc-9cf2-fb5c46a8d690"),
                            Amount = 20L,
                            Date = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("820daebd-f027-4a39-bbcb-289b2d161933")
                        },
                        new
                        {
                            Id = new Guid("6df9fe8c-81f6-4012-9cd1-770db162194c"),
                            Amount = 600L,
                            Date = new DateTime(2025, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b3b31e78-aeaf-468e-baca-3367045ae65b")
                        },
                        new
                        {
                            Id = new Guid("b6725f2b-1a51-4725-ba39-00cd383cddd4"),
                            Amount = 100L,
                            Date = new DateTime(2025, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("5fd4afed-3409-4e18-8118-d0bcf847f11f")
                        },
                        new
                        {
                            Id = new Guid("5540ed12-0723-4860-8c7b-dc6d6be1476b"),
                            Amount = 400L,
                            Date = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d849a3fd-5e3a-4365-92df-79e59b732247")
                        },
                        new
                        {
                            Id = new Guid("7de6ee59-d547-4b16-a8a4-3ca184ef4cee"),
                            Amount = 300L,
                            Date = new DateTime(2025, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("3cd3e963-5f1c-4026-8cac-f8b097d2be02")
                        },
                        new
                        {
                            Id = new Guid("cb4fb4fe-092f-4f6a-8ccd-068f8b69abbc"),
                            Amount = 500L,
                            Date = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b9bf0cdb-2390-4f19-9955-db8bad50574f")
                        },
                        new
                        {
                            Id = new Guid("8949a8d2-fe81-429e-8646-c4741b1cf8d8"),
                            Amount = 500L,
                            Date = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("2ecb9915-51d2-48ed-a796-8b46f250274b"),
                            Amount = 100L,
                            Date = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e7d6760c-92d3-4130-b4d6-5ad459880399")
                        },
                        new
                        {
                            Id = new Guid("7c5e3fb9-a937-41e7-a783-cb8eb3c099aa"),
                            Amount = 750L,
                            Date = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("b924b2e9-f504-4bc6-a611-ce856b2b1fdd")
                        },
                        new
                        {
                            Id = new Guid("bb64640b-9caa-4561-ade6-4411d8669369"),
                            Amount = 120L,
                            Date = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("07833ef4-9b71-4457-92f1-8cd3ea331630")
                        },
                        new
                        {
                            Id = new Guid("2aa80a14-7db2-4d10-9735-f4b6e41c9b4c"),
                            Amount = 1500L,
                            Date = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("d8179f7e-9789-4be3-a1c2-5c536c5d384b")
                        },
                        new
                        {
                            Id = new Guid("69acb819-94f8-4c83-98f2-74d9cced9982"),
                            Amount = 60L,
                            Date = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("663171ac-1ac1-461d-b45a-469e644c9ae4")
                        },
                        new
                        {
                            Id = new Guid("9012c5a2-50db-4b0a-a542-d00f350e0858"),
                            Amount = 40L,
                            Date = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("cc488c25-5e5d-4ae1-9cca-7842effad853")
                        },
                        new
                        {
                            Id = new Guid("88cdf2aa-af1b-48e1-a8d3-706aaebe25bf"),
                            Amount = 100L,
                            Date = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e21e180c-29e3-412a-99f3-b7254a6c6a1b")
                        },
                        new
                        {
                            Id = new Guid("232c889e-917a-4224-8e11-c420326ba1bc"),
                            Amount = 2000L,
                            Date = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("e95da595-58b3-4726-97b7-d752323d594e")
                        },
                        new
                        {
                            Id = new Guid("0da8a758-6b04-4a19-8cca-899c0c69e168"),
                            Amount = 300L,
                            Date = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("afd56f2e-2660-4363-9321-645d93fa0520")
                        },
                        new
                        {
                            Id = new Guid("431411c3-7aea-438f-b6f8-4be16a0a0d38"),
                            Amount = 2000L,
                            Date = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("2b451831-90df-4fc3-91a2-471855873ba6"),
                            Amount = 300L,
                            Date = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        },
                        new
                        {
                            Id = new Guid("83290696-5e39-4f2b-9fac-daa092452f03"),
                            Amount = 100L,
                            Date = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b")
                        });
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("FinanceOperationTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f20e1cd9-84e1-4fc0-be9d-0b830d1be20b"),
                            Description = "Monthly salary",
                            EntryType = 0,
                            Name = "Salary",
                            WalletId = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1")
                        },
                        new
                        {
                            Id = new Guid("b9bf0cdb-2390-4f19-9955-db8bad50574f"),
                            Description = "Income from tax refund",
                            EntryType = 0,
                            Name = "Tax Refund",
                            WalletId = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1")
                        },
                        new
                        {
                            Id = new Guid("e7d6760c-92d3-4130-b4d6-5ad459880399"),
                            Description = "Weekly groceries",
                            EntryType = 1,
                            Name = "Groceries",
                            WalletId = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1")
                        },
                        new
                        {
                            Id = new Guid("3d033511-8700-4f2a-a6f2-e47ce51e2bf3"),
                            Description = "Monthly internet bill",
                            EntryType = 1,
                            Name = "Internet Bill",
                            WalletId = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1")
                        },
                        new
                        {
                            Id = new Guid("0ebd2a28-9726-4f28-b5a9-707410ef2ad2"),
                            Description = "Annual bonus",
                            EntryType = 0,
                            Name = "Bonus",
                            WalletId = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1")
                        },
                        new
                        {
                            Id = new Guid("b924b2e9-f504-4bc6-a611-ce856b2b1fdd"),
                            Description = "Monthly rent payment",
                            EntryType = 1,
                            Name = "Rent",
                            WalletId = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf")
                        },
                        new
                        {
                            Id = new Guid("07833ef4-9b71-4457-92f1-8cd3ea331630"),
                            Description = "Monthly electricity bill",
                            EntryType = 1,
                            Name = "Electricity Bill",
                            WalletId = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf")
                        },
                        new
                        {
                            Id = new Guid("2b9da575-54ea-4689-bae0-cfe923ac47b2"),
                            Description = "Income from book sales",
                            EntryType = 0,
                            Name = "Book Sales",
                            WalletId = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf")
                        },
                        new
                        {
                            Id = new Guid("76dda505-b8db-4980-8156-ce3056018b97"),
                            Description = "Health insurance payment",
                            EntryType = 1,
                            Name = "Insurance",
                            WalletId = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf")
                        },
                        new
                        {
                            Id = new Guid("820daebd-f027-4a39-bbcb-289b2d161933"),
                            Description = "Monthly subscriptions",
                            EntryType = 1,
                            Name = "Subscriptions",
                            WalletId = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf")
                        },
                        new
                        {
                            Id = new Guid("d8179f7e-9789-4be3-a1c2-5c536c5d384b"),
                            Description = "Freelance project payment",
                            EntryType = 0,
                            Name = "Freelance",
                            WalletId = new Guid("9d536894-4aca-4df0-bdf4-8096fd142de9")
                        },
                        new
                        {
                            Id = new Guid("02261ce9-14ba-478b-b522-2cc28790ecf7"),
                            Description = "Bank account interest",
                            EntryType = 0,
                            Name = "Interest",
                            WalletId = new Guid("9d536894-4aca-4df0-bdf4-8096fd142de9")
                        },
                        new
                        {
                            Id = new Guid("629021c3-fe72-447a-b80a-33670d2f8bbd"),
                            Description = "Purchase of clothing",
                            EntryType = 1,
                            Name = "Clothing",
                            WalletId = new Guid("9d536894-4aca-4df0-bdf4-8096fd142de9")
                        },
                        new
                        {
                            Id = new Guid("663171ac-1ac1-461d-b45a-469e644c9ae4"),
                            Description = "Dinner at restaurant",
                            EntryType = 1,
                            Name = "Dining Out",
                            WalletId = new Guid("9d536894-4aca-4df0-bdf4-8096fd142de9")
                        },
                        new
                        {
                            Id = new Guid("4b3af6df-8abe-42a1-82e0-ae861a9a33ed"),
                            Description = "Birthday gift",
                            EntryType = 1,
                            Name = "Gift",
                            WalletId = new Guid("2cdd231c-4fc1-47ef-be64-c93e2b6aa842")
                        },
                        new
                        {
                            Id = new Guid("e95da595-58b3-4726-97b7-d752323d594e"),
                            Description = "Monthly gym membership",
                            EntryType = 1,
                            Name = "Gym Membership",
                            WalletId = new Guid("2cdd231c-4fc1-47ef-be64-c93e2b6aa842")
                        },
                        new
                        {
                            Id = new Guid("f51e1eb6-539a-4e71-9e12-4d8c50fd92b2"),
                            Description = "Payment for medical services",
                            EntryType = 1,
                            Name = "Medical Bills",
                            WalletId = new Guid("2cdd231c-4fc1-47ef-be64-c93e2b6aa842")
                        },
                        new
                        {
                            Id = new Guid("afd56f2e-2660-4363-9321-645d93fa0520"),
                            Description = "Payment for education",
                            EntryType = 1,
                            Name = "Tuition",
                            WalletId = new Guid("2cdd231c-4fc1-47ef-be64-c93e2b6aa842")
                        },
                        new
                        {
                            Id = new Guid("eb00cc66-2104-4bc4-9d6b-fc20f2cdc935"),
                            Description = "Income from software sales",
                            EntryType = 0,
                            Name = "Software Sales",
                            WalletId = new Guid("537e8323-bdba-41f2-a141-5a3f024978ea")
                        },
                        new
                        {
                            Id = new Guid("b3b31e78-aeaf-468e-baca-3367045ae65b"),
                            Description = "Consulting services",
                            EntryType = 0,
                            Name = "Consulting",
                            WalletId = new Guid("537e8323-bdba-41f2-a141-5a3f024978ea")
                        },
                        new
                        {
                            Id = new Guid("4af51eea-e862-4caf-8ce5-9ad6737dbd7b"),
                            Description = "Purchase of household supplies",
                            EntryType = 1,
                            Name = "Household Supplies",
                            WalletId = new Guid("537e8323-bdba-41f2-a141-5a3f024978ea")
                        },
                        new
                        {
                            Id = new Guid("5fd4afed-3409-4e18-8118-d0bcf847f11f"),
                            Description = "Travel expenses",
                            EntryType = 1,
                            Name = "Travel",
                            WalletId = new Guid("537e8323-bdba-41f2-a141-5a3f024978ea")
                        },
                        new
                        {
                            Id = new Guid("e1941e45-3981-454d-af77-46be20eb8f90"),
                            Description = "Stock dividends",
                            EntryType = 0,
                            Name = "Dividends",
                            WalletId = new Guid("ccb6d53b-ae14-44a4-ab75-525b838786fe")
                        },
                        new
                        {
                            Id = new Guid("3cd3e963-5f1c-4026-8cac-f8b097d2be02"),
                            Description = "Income from freelance writing",
                            EntryType = 0,
                            Name = "Freelance Writing",
                            WalletId = new Guid("ccb6d53b-ae14-44a4-ab75-525b838786fe")
                        },
                        new
                        {
                            Id = new Guid("ce0b9d6d-d470-4cc2-8d3e-5ad21aca29a4"),
                            Description = "Stock market investment",
                            EntryType = 1,
                            Name = "Investment",
                            WalletId = new Guid("ccb6d53b-ae14-44a4-ab75-525b838786fe")
                        },
                        new
                        {
                            Id = new Guid("d849a3fd-5e3a-4365-92df-79e59b732247"),
                            Description = "Donation to charity",
                            EntryType = 1,
                            Name = "Charity",
                            WalletId = new Guid("ccb6d53b-ae14-44a4-ab75-525b838786fe")
                        },
                        new
                        {
                            Id = new Guid("e21e180c-29e3-412a-99f3-b7254a6c6a1b"),
                            Description = "Monthly savings",
                            EntryType = 0,
                            Name = "Savings",
                            WalletId = new Guid("d3d06754-3f13-4cd1-ae8b-4bc95db7490d")
                        },
                        new
                        {
                            Id = new Guid("cc488c25-5e5d-4ae1-9cca-7842effad853"),
                            Description = "Income from music sales",
                            EntryType = 0,
                            Name = "Music Sales",
                            WalletId = new Guid("d3d06754-3f13-4cd1-ae8b-4bc95db7490d")
                        },
                        new
                        {
                            Id = new Guid("6ae5a115-3361-4b6f-84cb-61fd53f18358"),
                            Description = "Car repair and maintenance",
                            EntryType = 1,
                            Name = "Car Maintenance",
                            WalletId = new Guid("d3d06754-3f13-4cd1-ae8b-4bc95db7490d")
                        },
                        new
                        {
                            Id = new Guid("adcbf657-efee-4666-a179-e5a105a1b99d"),
                            Description = "Purchase of furniture",
                            EntryType = 1,
                            Name = "Furniture",
                            WalletId = new Guid("d3d06754-3f13-4cd1-ae8b-4bc95db7490d")
                        });
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8d6f6da-cd32-4c0c-9f16-d9c362f2f4c1"),
                            Balance = 1000,
                            Name = "Primary Wallet",
                            UserId = new Guid("06a12d9c-20a2-4f39-8c13-68e0bdddbadb")
                        },
                        new
                        {
                            Id = new Guid("2dd4c61c-b85b-48d7-a746-da3f67900aaf"),
                            Balance = 1500,
                            Name = "Savings Wallet",
                            UserId = new Guid("06a12d9c-20a2-4f39-8c13-68e0bdddbadb")
                        },
                        new
                        {
                            Id = new Guid("9d536894-4aca-4df0-bdf4-8096fd142de9"),
                            Balance = 2000,
                            Name = "Investment Wallet",
                            UserId = new Guid("6085ec7e-1cd3-4302-a51e-0a216c738b79")
                        },
                        new
                        {
                            Id = new Guid("2cdd231c-4fc1-47ef-be64-c93e2b6aa842"),
                            Balance = 3000,
                            Name = "Emergency Fund",
                            UserId = new Guid("b9d052fd-c677-4722-85ff-0a2a5aad4af1")
                        },
                        new
                        {
                            Id = new Guid("537e8323-bdba-41f2-a141-5a3f024978ea"),
                            Balance = 3500,
                            Name = "Retirement Fund",
                            UserId = new Guid("47b38d98-ee54-409b-bf0b-2821ca8a20b0")
                        },
                        new
                        {
                            Id = new Guid("ccb6d53b-ae14-44a4-ab75-525b838786fe"),
                            Balance = 4000,
                            Name = "Education Fund",
                            UserId = new Guid("00039684-7db3-46ff-a0f5-b744f225c30e")
                        },
                        new
                        {
                            Id = new Guid("d3d06754-3f13-4cd1-ae8b-4bc95db7490d"),
                            Balance = 2500,
                            Name = "Vacation Fund",
                            UserId = new Guid("00039684-7db3-46ff-a0f5-b744f225c30e")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("06a12d9c-20a2-4f39-8c13-68e0bdddbadb"),
                            RoleId = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85")
                        },
                        new
                        {
                            UserId = new Guid("6085ec7e-1cd3-4302-a51e-0a216c738b79"),
                            RoleId = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85")
                        },
                        new
                        {
                            UserId = new Guid("b9d052fd-c677-4722-85ff-0a2a5aad4af1"),
                            RoleId = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85")
                        },
                        new
                        {
                            UserId = new Guid("47b38d98-ee54-409b-bf0b-2821ca8a20b0"),
                            RoleId = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85")
                        },
                        new
                        {
                            UserId = new Guid("00039684-7db3-46ff-a0f5-b744f225c30e"),
                            RoleId = new Guid("2da1dfa4-5d4d-45eb-895c-1c82b5971b85")
                        },
                        new
                        {
                            UserId = new Guid("0c2fb4ea-d631-4ce7-9f02-2f4c011c2160"),
                            RoleId = new Guid("db3e695c-2f84-47ec-8a36-8e2c51b7a53f")
                        },
                        new
                        {
                            UserId = new Guid("1749fadd-b32e-430d-80d4-68b041218bd3"),
                            RoleId = new Guid("db3e695c-2f84-47ec-8a36-8e2c51b7a53f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.FinanceOperation", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.FinanceOperationType", "Type")
                        .WithMany("FinanceOperations")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Wallet", "Wallet")
                        .WithMany("FinanceOperationTypes")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Wallet", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Authorization.FinanceManagerUser", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.Navigation("FinanceOperations");
                });

            modelBuilder.Entity("FinanceManager.Infrastructure.Models.Wallet", b =>
                {
                    b.Navigation("FinanceOperationTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
