<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FinanceManager.ApiService\FinanceManager.ApiService.csproj" />
    <ProjectReference Include="..\FinanceManager.AppHost\FinanceManager.AppHost.csproj" />
    <ProjectReference Include="..\FinanceManager.Application\FinanceManager.Application.csproj" />
    <ProjectReference Include="..\FinanceManager.Domain\FinanceManager.Domain.csproj" />
    <ProjectReference Include="..\FinanceManager.Infrastructure\FinanceManager.Infrastructure.csproj" />
    <ProjectReference Include="..\FinanceManager.ServiceDefaults\FinanceManager.ServiceDefaults.csproj" />
    <ProjectReference Include="..\FinanceManager.Web\FinanceManager.Web.csproj" />
  </ItemGroup>


</Project>
